# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - simple-commerce-web-app-stan-docelowy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build ./SimpleCommerce/SimpleCommerce.csproj  --configuration Release

      - name: dotnet publish
        run: dotnet publish ./SimpleCommerce/SimpleCommerce.csproj -c Release -o ./myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_990CE85A417D444FBD146531CA3245AE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_44CD196D13CE4AE48BDE403120168BD8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B4E2E53BEA8A4F34A816908CA907B9E0 }}

      - name: Set Environment Variable for Web App
        shell: pwsh
        run: |
          $secretValue = az keyvault secret show --vault-name keyvaultstandocelowy `
            --name database-connection-string-passwrodless `
            --query value -o tsv
          az webapp config appsettings set `
            --name simple-commerce-web-app-stan-docelowy `
            --resource-group zajecia-azure-stan-docelowy `
            --settings Infrastructure:ConnectionString=${{ env.DATABASE_CONNECTION_STRING }}
          az webapp/logicapp/functionapp config appsettings list
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'simple-commerce-web-app-stan-docelowy'
          slot-name: 'Production'
          package: .
          # Infrastructure:ConnectionString: $(mySecret)
